from flock.core import Flock, FlockFactory

# from flock.core.logging import configure_logging
# configure_logging(flock_level="DEBUG",external_level="DEBUG")

MODEL = "azure/gpt-4.1"

flock = Flock(name="scheduled_flock", description="This is a scheduled flock", model=MODEL)

my_joke_per_minute_agent = FlockFactory.create_scheduled_agent(
    name="my_joke_per_minute_agent",
    schedule_expression="every 10s",
    description="This agent generates a funny joke every minute.",
    input="my_joke_per_minute_agent.a_funny_joke : str | The last joke generated by the agent.",
    output="a_funny_joke",
    temperature=1
)

flock.add_agent(my_joke_per_minute_agent)

# The scheduler hooks into the FastAPI lifespan cycle
flock.serve()

